/**
 * Curated MCP server catalog — a static list of high-value MCP servers
 * sourced from PulseMCP (pulsemcp.com/servers). This replaces the need for
 * a live API integration; the catalog can be updated periodically.
 *
 * Each entry contains enough metadata to construct an MCPServerConfig at
 * install time and to render a store card in the UI.
 */

export type MCPTransport = "remote" | "stdio";

export type MCPAuthType = "open" | "oauth" | "apikey";

export interface MCPCatalogServer {
  /** Unique slug identifier. */
  id: string;
  /** Display name. */
  name: string;
  /** Short one-line summary for card view. */
  summary: string;
  /** Full description for detail view. */
  description: string;
  /** Transport type — remote (HTTP/SSE) or stdio (local process). */
  transport: MCPTransport;
  /** Auth method required. */
  authType: MCPAuthType;
  /** Whether this is an official server from the service provider. */
  isOfficial: boolean;
  /** Category tags for filtering. */
  category: string[];
  /** Brand logo URL (from simpleicons.org CDN) or inline SVG string for non-branded servers. */
  icon: string;
  /** Estimated weekly visitors (from PulseMCP, approximate). */
  visitorsPerWeek?: string;
  /** For remote servers: the MCP endpoint URL. */
  url?: string;
  /** For stdio servers: the command to spawn. */
  command?: string;
  /** For stdio servers: arguments for the command. */
  args?: string[];
  /** Environment variables the user may need to provide. */
  envVars?: { name: string; description: string; isRequired: boolean }[];
  /** Whether this server is suitable for native game integration (visual). */
  nativeIntegration?: boolean;
  /** Description of the native game integration, if applicable. */
  nativeIntegrationNote?: string;
  /** What to call the credential in the UI (e.g. "Personal Access Token", "Secret Key"). Falls back to "API Key". */
  keyLabel?: string;
  /** Placeholder text for the key input (e.g. "ghp_...", "sk_live_..."). Falls back to "Paste API key...". */
  keyPlaceholder?: string;
  /** URL where users can create/obtain their key. Renders as a "Get your key →" link. */
  keyHelpUrl?: string;
}

export const MCP_CATALOG: MCPCatalogServer[] = [
  // ── Tier 1: Remote MCPs (Store Items) ────────────────────────────────

  {
    id: "notion",
    name: "Notion",
    summary: "Search content, query databases, manage pages and comments.",
    description:
      "Bridges to the Notion API for searching content, querying databases, and managing pages and comments without leaving the agent workspace. Agents can read docs, update databases, and create new pages.",
    transport: "remote",
    authType: "oauth",
    isOfficial: true,
    category: ["productivity", "knowledge"],
    icon: "https://cdn.simpleicons.org/notion/white",
    visitorsPerWeek: "120k",
    url: "https://mcp.notion.com/mcp",
  },
  {
    id: "github",
    name: "GitHub",
    summary: "Manage repositories, issues, pull requests, and search code.",
    description:
      "Manage repositories, issues, pull requests, and search code via GitHub API. Agents can create issues, review PRs, search across repos, and manage branches.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["development", "git"],
    icon: "https://cdn.simpleicons.org/github/white",
    visitorsPerWeek: "106k",
    url: "https://api.githubcopilot.com/mcp/",
    keyLabel: "Personal Access Token",
    keyPlaceholder: "ghp_...",
    keyHelpUrl: "https://github.com/settings/tokens",
  },
  {
    id: "linear",
    name: "Linear",
    summary: "Manage projects, issues, and cycles in Linear.",
    description:
      "Access your Linear data to manage your projects and issues in a simple and secure way. Agents can create issues, update status, view cycles, and track progress.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["productivity", "project-management"],
    icon: "https://cdn.simpleicons.org/linear",
    visitorsPerWeek: "66k",
    url: "https://mcp.linear.app/mcp",
    keyLabel: "API Key",
    keyPlaceholder: "lin_api_...",
    keyHelpUrl: "https://linear.app/settings/api",
  },
  {
    id: "slack",
    name: "Slack",
    summary: "Send messages, read channels, and manage Slack workspace.",
    description:
      "Integrates with Slack to enable agents to send messages, read channel history, search messages, and interact with your Slack workspace.",
    transport: "remote",
    authType: "oauth",
    isOfficial: true,
    category: ["communication", "productivity"],
    icon: "https://cdn.simpleicons.org/slack",
    visitorsPerWeek: "—",
    url: "https://mcp.slack.com/sse",
  },
  {
    id: "stripe",
    name: "Stripe",
    summary: "Payment processing, customer management, and financial ops.",
    description:
      "Integrates with Stripe's API to enable payment processing, customer management, and financial operations. Agents can create charges, manage customers, handle subscriptions, and query transaction data.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["finance", "payments"],
    icon: "https://cdn.simpleicons.org/stripe",
    visitorsPerWeek: "70k",
    url: "https://mcp.stripe.com",
    keyLabel: "Secret Key",
    keyPlaceholder: "sk_live_...",
    keyHelpUrl: "https://dashboard.stripe.com/apikeys",
  },
  {
    id: "figma",
    name: "Figma",
    summary: "Extract design info, variables, and component data.",
    description:
      "Integrates with Figma's desktop app to extract design information, variables, and component data from selected frames. Agents can read design specs, extract assets, and query design tokens.",
    transport: "remote",
    authType: "oauth",
    isOfficial: true,
    category: ["design", "development"],
    icon: "https://cdn.simpleicons.org/figma",
    visitorsPerWeek: "87k",
    url: "https://mcp.figma.com/mcp",
  },
  {
    id: "hubspot",
    name: "HubSpot",
    summary: "CRM contacts, companies, deals, and task management.",
    description:
      "Integrates with HubSpot CRM to enable secure access to contact information, company records, deal data, and task management. Agents can create contacts, update deals, and track pipeline.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["crm", "sales"],
    icon: "https://cdn.simpleicons.org/hubspot",
    visitorsPerWeek: "63k",
    url: "https://mcp.hubspot.com/mcp",
    keyLabel: "Private App Token",
    keyPlaceholder: "pat-...",
    keyHelpUrl: "https://app.hubspot.com/settings/api/private-apps",
  },
  {
    id: "grafana",
    name: "Grafana",
    summary: "Search dashboards, query Prometheus metrics, fetch data.",
    description:
      "Integrates with Grafana to enable searching dashboards, fetching datasource information, querying Prometheus metrics, and visualizing observability data.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["monitoring", "devops"],
    icon: "https://cdn.simpleicons.org/grafana",
    visitorsPerWeek: "140k",
    url: "https://mcp.grafana.com/sse",
    keyLabel: "Access Token",
    keyPlaceholder: "glsa_...",
    keyHelpUrl: "https://grafana.com/docs/grafana/latest/administration/service-accounts/",
  },
  {
    id: "mongodb",
    name: "MongoDB",
    summary: "Comprehensive database operations for MongoDB.",
    description:
      "Provides a bridge between MongoDB databases and conversational interfaces, enabling comprehensive database operations including CRUD, aggregation, and schema inspection.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["database", "data"],
    icon: "https://cdn.simpleicons.org/mongodb",
    visitorsPerWeek: "54k",
    url: "https://mcp.mongodb.com/sse",
    keyLabel: "API Key",
    keyPlaceholder: "Paste API key...",
    keyHelpUrl: "https://www.mongodb.com/docs/atlas/app-services/authentication/api-key/",
  },
  {
    id: "firecrawl",
    name: "FireCrawl",
    summary: "Advanced web scraping for extracting structured data.",
    description:
      "Integration with FireCrawl to provide advanced web scraping capabilities for extracting structured data from complex websites. Agents can crawl sites, extract content, and convert pages to markdown.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["web", "data"],
    icon: "https://cdn.simpleicons.org/firecrawl",
    visitorsPerWeek: "92k",
    url: "https://mcp.firecrawl.dev/sse",
    keyLabel: "API Key",
    keyPlaceholder: "fc-...",
    keyHelpUrl: "https://www.firecrawl.dev/app/api-keys",
  },
  {
    id: "n8n",
    name: "n8n",
    summary: "Workflow automation with 525+ integration nodes.",
    description:
      "Integrates with n8n workflow automation platform to provide conversational access to 525+ nodes including AI-capable ones. Agents can create, trigger, and manage automated workflows.",
    transport: "remote",
    authType: "apikey",
    isOfficial: false,
    category: ["automation", "productivity"],
    icon: "https://cdn.simpleicons.org/n8n",
    visitorsPerWeek: "122k",
    url: "https://mcp.n8n.io/sse",
    keyLabel: "API Key",
    keyPlaceholder: "n8n_api_...",
    keyHelpUrl: "https://docs.n8n.io/advanced-features/api/",
  },
  {
    id: "vercel",
    name: "Vercel",
    summary: "Deployment management and project operations.",
    description:
      "Manage Vercel deployments, projects, and environments. Agents can deploy, check deployment status, manage environment variables, and view analytics.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["devops", "hosting"],
    icon: "https://cdn.simpleicons.org/vercel/white",
    visitorsPerWeek: "—",
    url: "https://mcp.vercel.com/sse",
    keyLabel: "Access Token",
    keyPlaceholder: "vercel_...",
    keyHelpUrl: "https://vercel.com/account/tokens",
  },
  {
    id: "supabase",
    name: "Supabase",
    summary: "Manage databases, projects, migrations, and storage.",
    description:
      "Integrates with the Supabase platform for managing databases, projects, migrations, and storage. Agents can run SQL, manage tables, handle auth, and deploy edge functions.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["database", "backend"],
    icon: "https://cdn.simpleicons.org/supabase",
    visitorsPerWeek: "93k",
    url: "https://mcp.supabase.com/mcp",
    keyLabel: "Access Token",
    keyPlaceholder: "sbp_...",
    keyHelpUrl: "https://supabase.com/dashboard/account/tokens",
  },
  {
    id: "gitlab",
    name: "GitLab",
    summary: "Repo management, merge requests, issues, and CI/CD.",
    description:
      "Official GitLab MCP server for repository management, issue tracking, merge request handling, and CI/CD pipelines. Agents can create MRs, review code, and manage pipelines.",
    transport: "remote",
    authType: "oauth",
    isOfficial: true,
    category: ["development", "git"],
    icon: "https://cdn.simpleicons.org/gitlab",
    visitorsPerWeek: "62k",
    url: "https://gitlab.com/api/v4/mcp",
  },
  {
    id: "brave-search",
    name: "Brave Search",
    summary: "Web and local search via Brave Search API.",
    description:
      "Enables agents to perform web searches and local business searches using the Brave Search API. Good for research tasks, fact-checking, and finding current information.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["search", "web"],
    icon: "https://cdn.simpleicons.org/brave",
    visitorsPerWeek: "—",
    url: "https://mcp.brave.com/sse",
    keyLabel: "API Key",
    keyPlaceholder: "BSA...",
    keyHelpUrl: "https://brave.com/search/api/",
  },
  {
    id: "tavily",
    name: "Tavily",
    summary: "AI-optimized web search and extraction.",
    description:
      "AI-optimized search API that returns clean, relevant results for agent consumption. Supports search, extract, and crawl operations.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["search", "web"],
    icon: "<svg viewBox='0 0 24 24' fill='none' stroke='#e0e0e0' stroke-width='1.5' stroke-linecap='round' stroke-linejoin='round'><circle cx='11' cy='11' r='8'/><line x1='21' y1='21' x2='16.65' y2='16.65'/><line x1='11' y1='8' x2='11' y2='14'/><line x1='8' y1='11' x2='14' y2='11'/></svg>",
    visitorsPerWeek: "—",
    url: "https://mcp.tavily.com/mcp",
    keyLabel: "API Key",
    keyPlaceholder: "tvly-...",
    keyHelpUrl: "https://app.tavily.com/api-key",
  },

  // ── Tier 2: Local MCPs (Native Game Integration Candidates) ──────────

  {
    id: "playwright",
    name: "Playwright",
    summary: "Browser automation — navigate, click, screenshot, fill forms.",
    description:
      "Microsoft's official MCP server for browser automation. Agents can navigate websites, capture page snapshots, interact with elements, take screenshots, and fill forms. The #1 most-visited MCP server on PulseMCP (5.5M weekly visitors).",
    transport: "stdio",
    authType: "open",
    isOfficial: true,
    category: ["browser", "automation", "development"],
    icon: "https://cdn.simpleicons.org/playwright",
    visitorsPerWeek: "5.5M",
    command: "npx",
    args: ["-y", "@anthropic-ai/mcp-server-playwright"],
    nativeIntegration: true,
    nativeIntegrationNote:
      "Browser station: render a live browser viewport on the agent's desk monitor. Player watches the agent navigate pages, click elements, and fill forms in real-time.",
  },
  {
    id: "chrome-devtools",
    name: "Chrome DevTools",
    summary: "Direct Chrome browser control for automation and debugging.",
    description:
      "Google's official MCP server providing direct Chrome browser control through DevTools for web automation, debugging, and performance analysis. Pairs well with Playwright.",
    transport: "stdio",
    authType: "open",
    isOfficial: true,
    category: ["browser", "automation", "development"],
    icon: "https://cdn.simpleicons.org/googlechrome",
    visitorsPerWeek: "2M",
    command: "npx",
    args: ["-y", "@anthropic-ai/mcp-server-chrome-devtools"],
    nativeIntegration: true,
    nativeIntegrationNote:
      "DevTools panel: show network requests, console output, and performance graphs on the agent's monitor alongside Playwright.",
  },
  {
    id: "sequential-thinking",
    name: "Sequential Thinking",
    summary: "Structured problem decomposition with iterative refinement.",
    description:
      "Implements a structured sequential thinking process for breaking down complex problems, iteratively refining ideas, and tracking reasoning steps. Agents can think through multi-step problems methodically.",
    transport: "stdio",
    authType: "open",
    isOfficial: true,
    category: ["reasoning", "ai"],
    icon: "<svg viewBox='0 0 24 24' fill='none' stroke='#e0e0e0' stroke-width='1.5' stroke-linecap='round' stroke-linejoin='round'><path d='M9.5 2A2.5 2.5 0 0 1 12 4.5v15a2.5 2.5 0 0 1-4.96.44 2.5 2.5 0 0 1-2.96-3.08 3 3 0 0 1-.34-5.58 2.5 2.5 0 0 1 1.32-4.24 2.5 2.5 0 0 1 1.98-3A2.5 2.5 0 0 1 9.5 2Z'/><path d='M14.5 2A2.5 2.5 0 0 0 12 4.5v15a2.5 2.5 0 0 0 4.96.44 2.5 2.5 0 0 0 2.96-3.08 3 3 0 0 0 .34-5.58 2.5 2.5 0 0 0-1.32-4.24 2.5 2.5 0 0 0-1.98-3A2.5 2.5 0 0 0 14.5 2Z'/></svg>",
    visitorsPerWeek: "195k",
    command: "npx",
    args: ["-y", "@anthropic-ai/mcp-server-sequential-thinking"],
    nativeIntegration: true,
    nativeIntegrationNote:
      "Thought bubbles: show reasoning steps as thought bubbles above the agent's head as they work through complex problems. Each step appears as a new bubble.",
  },
  {
    id: "knowledge-graph-memory",
    name: "Knowledge Graph Memory",
    summary: "Persistent semantic memory networks for agents.",
    description:
      "Build and query persistent semantic networks for data management. Agents can store entities, relationships, and observations — creating a long-term memory that persists across tasks.",
    transport: "stdio",
    authType: "open",
    isOfficial: true,
    category: ["memory", "ai"],
    icon: "<svg viewBox='0 0 24 24' fill='none' stroke='#e0e0e0' stroke-width='1.2' stroke-linecap='round'><circle cx='12' cy='12' r='2'/><circle cx='12' cy='4' r='1.5'/><circle cx='12' cy='20' r='1.5'/><circle cx='4' cy='12' r='1.5'/><circle cx='20' cy='12' r='1.5'/><circle cx='6' cy='6' r='1.5'/><circle cx='18' cy='6' r='1.5'/><circle cx='6' cy='18' r='1.5'/><circle cx='18' cy='18' r='1.5'/><line x1='12' y1='12' x2='12' y2='4'/><line x1='12' y1='12' x2='12' y2='20'/><line x1='12' y1='12' x2='4' y2='12'/><line x1='12' y1='12' x2='20' y2='12'/><line x1='12' y1='12' x2='6' y2='6'/><line x1='12' y1='12' x2='18' y2='6'/><line x1='12' y1='12' x2='6' y2='18'/><line x1='12' y1='12' x2='18' y2='18'/><line x1='6' y1='6' x2='18' y2='6'/><line x1='18' y1='6' x2='18' y2='18'/><line x1='18' y1='18' x2='6' y2='18'/><line x1='6' y1='18' x2='6' y2='6'/></svg>",
    visitorsPerWeek: "113k",
    command: "npx",
    args: ["-y", "@anthropic-ai/mcp-server-memory"],
    nativeIntegration: true,
    nativeIntegrationNote:
      "Memory board: a corkboard in the office where agents pin things they've learned. Connected notes show relationships. Persists across tasks and sessions.",
  },
  {
    id: "context7",
    name: "Context7",
    summary: "Up-to-date library and framework documentation.",
    description:
      "Connects to Context7.com's documentation database to provide up-to-date library and framework documentation. Agents can look up API references, find usage examples, and resolve version-specific questions.",
    transport: "stdio",
    authType: "open",
    isOfficial: true,
    category: ["documentation", "development"],
    icon: "<svg viewBox='0 0 24 24' fill='none' stroke='#e0e0e0' stroke-width='1.5' stroke-linecap='round' stroke-linejoin='round'><path d='M4 19.5A2.5 2.5 0 0 1 6.5 17H20'/><path d='M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2Z'/><path d='M9 7h7'/><path d='M9 11h7'/></svg>",
    visitorsPerWeek: "998k",
    command: "npx",
    args: ["-y", "@upstash/context7-mcp"],
    nativeIntegration: true,
    nativeIntegrationNote:
      "Reference library: agents look up docs with a bookshelf animation. Doc content appears in a side panel when the agent pulls a 'book'.",
  },
  {
    id: "git",
    name: "Git",
    summary: "Interact with local Git repositories for version control.",
    description:
      "Interact with local Git repositories for version control tasks. Agents can check status, diff, commit, branch, log, and manage repository state.",
    transport: "stdio",
    authType: "open",
    isOfficial: true,
    category: ["development", "git"],
    icon: "https://cdn.simpleicons.org/git/white",
    visitorsPerWeek: "245k",
    command: "npx",
    args: ["-y", "@anthropic-ai/mcp-server-git"],
    nativeIntegration: true,
    nativeIntegrationNote:
      "Version control station: agents commit work with a visual 'saving' animation. Git log panel shows commit history in the office.",
  },
  {
    id: "storybook",
    name: "Storybook",
    summary: "Write and test UI component stories automatically.",
    description:
      "Help agents automatically write and test stories for your UI components. Agents can generate stories, run visual tests, and verify component behavior.",
    transport: "stdio",
    authType: "open",
    isOfficial: true,
    category: ["testing", "development", "ui"],
    icon: "https://cdn.simpleicons.org/storybook",
    visitorsPerWeek: "1.7M",
    command: "npx",
    args: ["-y", "@storybook/mcp-server"],
    nativeIntegration: true,
    nativeIntegrationNote:
      "Testing lab room: a dedicated room where agents write and run stories. Pass/fail results displayed on a screen. Gamify test coverage as a score.",
  },
  {
    id: "time",
    name: "Time",
    summary: "Timezone conversion and localized time tools.",
    description:
      "MCP server providing time and timezone conversion tools for AI assistants to handle localized time data and timezone-aware scheduling.",
    transport: "stdio",
    authType: "open",
    isOfficial: true,
    category: ["utility"],
    icon: "<svg viewBox='0 0 24 24' fill='none' stroke='#e0e0e0' stroke-width='1.5' stroke-linecap='round' stroke-linejoin='round'><circle cx='12' cy='12' r='10'/><polyline points='12 6 12 12 16 14'/></svg>",
    visitorsPerWeek: "92k",
    command: "npx",
    args: ["-y", "@anthropic-ai/mcp-server-time"],
    nativeIntegration: true,
    nativeIntegrationNote:
      "Wall clock: a clock in the office showing the current time. Minor but adds atmosphere and timezone awareness for scheduling agents.",
  },
  {
    id: "filesystem",
    name: "Filesystem",
    summary: "Read, write, and manipulate local files (controlled API).",
    description:
      "Read, write, and manipulate local files through a controlled API. Requires specifying allowed directories. Note: AgentHQ already has built-in file tools — this is for agents that need direct filesystem access outside the workspace sandbox.",
    transport: "stdio",
    authType: "open",
    isOfficial: true,
    category: ["filesystem", "development"],
    icon: "<svg viewBox='0 0 24 24' fill='none' stroke='#e0e0e0' stroke-width='1.5' stroke-linecap='round' stroke-linejoin='round'><path d='M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z'/></svg>",
    visitorsPerWeek: "525k",
    command: "npx",
    args: ["-y", "@anthropic-ai/mcp-server-filesystem"],
    envVars: [
      { name: "ALLOWED_DIRS", description: "Comma-separated list of directories the server can access", isRequired: true },
    ],
  },
  {
    id: "fetch",
    name: "Fetch",
    summary: "Retrieve and convert web content to markdown.",
    description:
      "Retrieve and convert web content to markdown for analysis. Note: AgentHQ agents already have a built-in web_fetch tool — this MCP provides a more robust fetching pipeline with better content extraction.",
    transport: "stdio",
    authType: "open",
    isOfficial: true,
    category: ["web", "utility"],
    icon: "<svg viewBox='0 0 24 24' fill='none' stroke='#e0e0e0' stroke-width='1.5' stroke-linecap='round' stroke-linejoin='round'><path d='M5 12.55a11 11 0 0 1 14.08 0'/><path d='M1.42 9a16 16 0 0 1 21.16 0'/><path d='M8.53 16.11a6 6 0 0 1 6.95 0'/><line x1='12' y1='20' x2='12.01' y2='20'/></svg>",
    visitorsPerWeek: "301k",
    command: "npx",
    args: ["-y", "@anthropic-ai/mcp-server-fetch"],
  },
  {
    id: "duckdb",
    name: "DuckDB",
    summary: "Execute SQL queries and analyze data in DuckDB.",
    description:
      "Execute SQL queries and analyze data in DuckDB databases. Lightweight, fast analytical database perfect for data analysis tasks.",
    transport: "stdio",
    authType: "open",
    isOfficial: false,
    category: ["database", "data", "analytics"],
    icon: "https://cdn.simpleicons.org/duckdb",
    visitorsPerWeek: "47k",
    command: "npx",
    args: ["-y", "@ktanaka101/mcp-server-duckdb"],
  },
  {
    id: "sqlite",
    name: "SQLite",
    summary: "Query and manage SQLite databases.",
    description:
      "Query and manage SQLite databases. Agents can run SQL, inspect schemas, and manage local database files.",
    transport: "stdio",
    authType: "open",
    isOfficial: true,
    category: ["database", "data"],
    icon: "https://cdn.simpleicons.org/sqlite/white",
    visitorsPerWeek: "—",
    command: "npx",
    args: ["-y", "@anthropic-ai/mcp-server-sqlite"],
  },
  {
    id: "memory-bank",
    name: "Memory Bank",
    summary: "Persistent project context and memory for agents.",
    description:
      "A persistent memory system that maintains project context across sessions. Agents can store decisions, track progress, and recall past work — ensuring continuity between tasks.",
    transport: "stdio",
    authType: "open",
    isOfficial: false,
    category: ["memory", "productivity"],
    icon: "<svg viewBox='0 0 24 24' fill='none' stroke='#e0e0e0' stroke-width='1.5' stroke-linecap='round' stroke-linejoin='round'><line x1='3' y1='22' x2='21' y2='22'/><line x1='6' y1='18' x2='6' y2='11'/><line x1='10' y1='18' x2='10' y2='11'/><line x1='14' y1='18' x2='14' y2='11'/><line x1='18' y1='18' x2='18' y2='11'/><polygon points='12 2 20 7 4 7'/></svg>",
    visitorsPerWeek: "—",
    command: "npx",
    args: ["-y", "@anthropic-ai/mcp-server-memory-bank"],
    nativeIntegration: true,
    nativeIntegrationNote:
      "Memory vault: a visual vault or filing cabinet in the office where agents store and retrieve project context. Shows what the agent 'remembers'.",
  },
  {
    id: "rag",
    name: "RAG",
    summary: "Retrieval-augmented generation over your documents.",
    description:
      "Provides retrieval-augmented generation capabilities, allowing agents to search and reference your document corpus for accurate, context-aware responses.",
    transport: "stdio",
    authType: "open",
    isOfficial: false,
    category: ["ai", "search", "documentation"],
    icon: "<svg viewBox='0 0 24 24' fill='none' stroke='#e0e0e0' stroke-width='1.5' stroke-linecap='round' stroke-linejoin='round'><path d='M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z'/><polyline points='14 2 14 8 20 8'/><line x1='9' y1='13' x2='15' y2='13'/><line x1='9' y1='17' x2='15' y2='17'/></svg>",
    visitorsPerWeek: "—",
    command: "npx",
    args: ["-y", "@anthropic-ai/mcp-server-rag"],
  },
  {
    id: "home-assistant",
    name: "Home Assistant",
    summary: "Control smart home devices, automations, and systems.",
    description:
      "Enables natural language control of Home Assistant smart home devices, automations, and system management. Agents can toggle lights, set temperatures, check sensors, and trigger automations.",
    transport: "remote",
    authType: "apikey",
    isOfficial: false,
    category: ["iot", "smart-home"],
    icon: "https://cdn.simpleicons.org/homeassistant",
    visitorsPerWeek: "123k",
    url: "https://mcp.home-assistant.io/sse",
    keyLabel: "Long-Lived Access Token",
    keyPlaceholder: "Paste access token...",
    keyHelpUrl: "https://www.home-assistant.io/docs/authentication/",
  },

  // ── Tier 3: Additional Remote MCPs from mcpservers.org ───────────────

  {
    id: "asana",
    name: "Asana",
    summary: "Tasks, projects, workspaces.",
    description: "Manage tasks, projects, and workspaces in Asana. Agents can create tasks, assign work, track project progress, and query workspace data.",
    transport: "remote",
    authType: "oauth",
    isOfficial: true,
    category: ["productivity", "project-management"],
    icon: "https://cdn.simpleicons.org/asana",
    url: "https://mcp.asana.com/sse",
  },
  {
    id: "atlassian",
    name: "Atlassian (Jira & Confluence)",
    summary: "Jira, Confluence, Compass — Atlassian suite.",
    description: "Official Atlassian MCP server for connecting AI agents to Jira, Confluence, Opsgenie, and other Atlassian products. Agents can manage issues, read docs, and track work.",
    transport: "remote",
    authType: "oauth",
    isOfficial: true,
    category: ["productivity", "project-management", "development"],
    icon: "https://cdn.simpleicons.org/atlassian/white",
    url: "https://mcp.atlassian.com/v1/sse",
  },
  {
    id: "canva",
    name: "Canva",
    summary: "Designs, assets, exports, comments.",
    description: "Create and manage designs, assets, exports, and comments in Canva. Agents can generate designs, export assets, and collaborate on visual content.",
    transport: "remote",
    authType: "oauth",
    isOfficial: true,
    category: ["design", "productivity"],
    icon: "https://cdn.simpleicons.org/canva",
    url: "https://mcp.canva.com/sse",
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    summary: "Workers, KV, R2, D1, DNS, account APIs.",
    description: "Deploy, configure, and interrogate your resources on the Cloudflare developer platform (Workers, KV, R2, D1, DNS). Agents can manage deployments, configure DNS, and inspect analytics.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["cloud", "devops", "hosting"],
    icon: "https://cdn.simpleicons.org/cloudflare/white",
    url: "https://docs.mcp.cloudflare.com/sse",
  },
  {
    id: "deepwiki",
    name: "DeepWiki by Devin",
    summary: "AI-powered codebase context and answers.",
    description: "Remote, no-auth MCP server providing AI-powered codebase context and answers. Agents can query any public GitHub repo for architecture, patterns, and implementation details.",
    transport: "remote",
    authType: "open",
    isOfficial: true,
    category: ["development", "documentation"],
    icon: "https://cdn.simpleicons.org/devin/white",
    url: "https://mcp.deepwiki.com/sse",
  },
  {
    id: "exa",
    name: "Exa",
    summary: "Web search + code docs search engine for AIs.",
    description: "Search Engine made for AIs by Exa. Agents can perform web searches, find code documentation, and retrieve relevant content with high precision.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["search", "web", "ai"],
    icon: "https://cdn.simpleicons.org/exa/white",
    url: "https://mcp.exa.ai/sse",
    keyLabel: "API Key",
    keyPlaceholder: "Paste API key...",
    keyHelpUrl: "https://dashboard.exa.ai/api-keys",
  },
  {
    id: "sentry",
    name: "Sentry",
    summary: "Search, query, and debug errors intelligently.",
    description: "Integrates with Sentry to enable agents to search, query, and debug errors. Agents can investigate issues, trace errors, and analyze performance metrics.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["monitoring", "devops", "development"],
    icon: "https://cdn.simpleicons.org/sentry",
    url: "https://mcp.sentry.dev/sse",
    keyLabel: "Auth Token",
    keyPlaceholder: "sntrys_...",
    keyHelpUrl: "https://sentry.io/settings/auth-tokens/",
  },
  {
    id: "posthog",
    name: "PostHog",
    summary: "Product analytics, flags, insights.",
    description: "Query and explore product analytics, feature flags, and user insights in PostHog. Agents can analyze funnels, retention, and user behavior data.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["analytics", "monitoring"],
    icon: "https://cdn.simpleicons.org/posthog",
    url: "https://mcp.posthog.com/sse",
    keyLabel: "Personal API Key",
    keyPlaceholder: "phx_...",
    keyHelpUrl: "https://us.posthog.com/settings/user-api-keys",
  },
  {
    id: "shopify",
    name: "Shopify",
    summary: "Build, manage, and analyze your Shopify store.",
    description: "Manage your Shopify store — products, orders, customers, inventory, and analytics. Agents can update product listings, process orders, and analyze sales data.",
    transport: "remote",
    authType: "oauth",
    isOfficial: true,
    category: ["commerce", "business"],
    icon: "https://cdn.simpleicons.org/shopify/white",
    url: "https://mcp.shopify.com/sse",
  },
  {
    id: "zapier",
    name: "Zapier",
    summary: "Actions across 8,000+ apps.",
    description: "Connect AI agents to Zapier's ecosystem of 8,000+ app integrations. Agents can create, trigger, and manage automated workflows across countless services.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["automation", "productivity"],
    icon: "https://cdn.simpleicons.org/zapier",
    url: "https://mcp.zapier.com/sse",
    keyLabel: "API Key",
    keyPlaceholder: "Paste API key...",
    keyHelpUrl: "https://developer.zapier.com/api/v1/docs/",
  },
  {
    id: "zoom",
    name: "Zoom",
    summary: "Meetings, recordings, summaries.",
    description: "Manage Zoom meetings, recordings, and summaries. Agents can schedule meetings, retrieve transcripts, and access meeting analytics.",
    transport: "remote",
    authType: "oauth",
    isOfficial: true,
    category: ["communication", "productivity"],
    icon: "https://cdn.simpleicons.org/zoom/white",
    url: "https://mcp.zoom.us/sse",
  },
  {
    id: "twilio",
    name: "Twilio",
    summary: "Build communications and customer engagement.",
    description: "Integrate with Twilio's communications platform. Agents can send SMS, make calls, manage phone numbers, and build customer engagement workflows.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["communication", "development"],
    icon: "https://cdn.simpleicons.org/twilio/red",
    url: "https://mcp.twilio.com/sse",
    keyLabel: "API Key",
    keyPlaceholder: "SK...",
    keyHelpUrl: "https://console.twilio.com/us1/account/keys",
  },
  {
    id: "paypal",
    name: "PayPal",
    summary: "Access PayPal payments platform.",
    description: "Integrate with PayPal's payments platform. Agents can create orders, process payments, manage transactions, and query payment history.",
    transport: "remote",
    authType: "oauth",
    isOfficial: true,
    category: ["finance", "payments"],
    icon: "https://cdn.simpleicons.org/paypal/white",
    url: "https://mcp.paypal.com/sse",
  },
  {
    id: "webflow",
    name: "Webflow",
    summary: "Sites, CMS, publishing.",
    description: "Manage Webflow sites, CMS collections, and publishing. Agents can update content, publish changes, and manage site structure.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["design", "hosting", "cms"],
    icon: "https://cdn.simpleicons.org/webflow/white",
    url: "https://mcp.webflow.com/sse",
    keyLabel: "Access Token",
    keyPlaceholder: "Paste access token...",
    keyHelpUrl: "https://developers.webflow.com/data/docs/access-tokens",
  },
  {
    id: "netlify",
    name: "Netlify",
    summary: "Create, deploy, manage, and secure websites.",
    description: "Manage Netlify sites, deployments, and configuration. Agents can deploy sites, check build status, manage environment variables, and configure domains.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["devops", "hosting"],
    icon: "https://cdn.simpleicons.org/netlify/white",
    url: "https://mcp.netlify.com/sse",
    keyLabel: "Access Token",
    keyPlaceholder: "nfp_...",
    keyHelpUrl: "https://app.netlify.com/user/applications",
  },
  {
    id: "airtable",
    name: "Airtable",
    summary: "Bring your structured data to AI agents.",
    description: "Access Airtable bases, tables, and records. Agents can query data, create records, update fields, and manage structured data across your organization.",
    transport: "remote",
    authType: "oauth",
    isOfficial: true,
    category: ["productivity", "database", "data"],
    icon: "https://cdn.simpleicons.org/airtable",
    url: "https://mcp.airtable.com/sse",
  },
  {
    id: "clickup",
    name: "ClickUp",
    summary: "Project management & collaboration for teams & agents.",
    description: "Manage projects, tasks, and workflows in ClickUp. Agents can create tasks, update statuses, manage sprints, and track team productivity.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["productivity", "project-management"],
    icon: "https://cdn.simpleicons.org/clickup",
    url: "https://mcp.clickup.com/sse",
    keyLabel: "API Key",
    keyPlaceholder: "pk_...",
    keyHelpUrl: "https://app.clickup.com/settings/apps",
  },
  {
    id: "calendly",
    name: "Calendly",
    summary: "Scheduling, events, availability.",
    description: "Manage Calendly scheduling, events, and availability. Agents can create meeting types, check availability, and schedule appointments.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["productivity", "scheduling"],
    icon: "https://cdn.simpleicons.org/calendly",
    url: "https://mcp.calendly.com/sse",
    keyLabel: "API Key",
    keyPlaceholder: "Paste API key...",
    keyHelpUrl: "https://calendly.com/integrations/api_webhooks",
  },
  {
    id: "cal-com",
    name: "Cal.com",
    summary: "Connect AI clients to Cal.com scheduling.",
    description: "Connect to Cal.com scheduling through the Model Context Protocol. Agents can manage events, check availability, and book meetings.",
    transport: "remote",
    authType: "oauth",
    isOfficial: true,
    category: ["productivity", "scheduling"],
    icon: "https://cdn.simpleicons.org/calcom/white",
    url: "https://mcp.cal.com/sse",
  },
  {
    id: "hugging-face",
    name: "Hugging Face",
    summary: "Access the HF Hub and thousands of Gradio Apps.",
    description: "Access the Hugging Face Hub — models, datasets, spaces, and thousands of Gradio apps. Agents can search models, run inference, and explore ML resources.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["ai", "ml", "development"],
    icon: "https://cdn.simpleicons.org/huggingface",
    url: "https://huggingface.co/mcp/sse",
    keyLabel: "Access Token",
    keyPlaceholder: "hf_...",
    keyHelpUrl: "https://huggingface.co/settings/tokens",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    summary: "Models, pricing, credits, test prompts.",
    description: "Access OpenRouter's model marketplace. Agents can query available models, check pricing, manage credits, and run test prompts across multiple LLM providers.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["ai", "development"],
    icon: "https://cdn.simpleicons.org/openrouter/white",
    url: "https://mcp.openrouter.ai/sse",
    keyLabel: "API Key",
    keyPlaceholder: "sk-or-...",
    keyHelpUrl: "https://openrouter.ai/keys",
  },
  {
    id: "postman",
    name: "Postman",
    summary: "Give API context to your coding agents.",
    description: "Access Postman collections, environments, and API definitions. Agents can inspect API specs, run requests, and manage test suites.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["development", "api"],
    icon: "https://cdn.simpleicons.org/postman/white",
    url: "https://mcp.postman.com/sse",
    keyLabel: "API Key",
    keyPlaceholder: "PMAK-...",
    keyHelpUrl: "https://postman.postman.co/settings/me/api-keys",
  },
  {
    id: "miro",
    name: "Miro",
    summary: "Access and create new content on Miro boards.",
    description: "Access and create content on Miro whiteboards. Agents can read board content, create sticky notes, and manage visual collaboration spaces.",
    transport: "remote",
    authType: "oauth",
    isOfficial: true,
    category: ["design", "productivity"],
    icon: "https://cdn.simpleicons.org/miro/white",
    url: "https://mcp.miro.com/sse",
  },
  {
    id: "lucid",
    name: "Lucid",
    summary: "Ideate, diagram, and align teams.",
    description: "Create and manage diagrams in Lucid. Agents can generate flowcharts, organizational charts, and visual documentation to align teams.",
    transport: "remote",
    authType: "oauth",
    isOfficial: true,
    category: ["design", "productivity"],
    icon: "https://cdn.simpleicons.org/lucid/white",
    url: "https://mcp.lucid.co/sse",
  },
  {
    id: "tldraw",
    name: "tldraw",
    summary: "Diagrams and whiteboards.",
    description: "Create and manage diagrams and whiteboards in tldraw. Agents can generate visual content, manipulate shapes, and collaborate on drawings.",
    transport: "remote",
    authType: "open",
    isOfficial: true,
    category: ["design", "productivity"],
    icon: "https://cdn.simpleicons.org/tldraw/white",
    url: "https://mcp.tldraw.com/sse",
  },
  {
    id: "mermaid-chart",
    name: "Mermaid Chart",
    summary: "Validates Mermaid syntax, renders diagrams as SVG.",
    description: "Validates Mermaid syntax, renders diagrams as high-quality SVG, and displays them in an interactive UI. Agents can create and iterate on diagram code.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["design", "development"],
    icon: "https://cdn.simpleicons.org/mermaid/white",
    url: "https://mcp.mermaidchart.com/sse",
    keyLabel: "API Key",
    keyPlaceholder: "Paste API key...",
    keyHelpUrl: "https://www.mermaidchart.com/app/settings/api-keys",
  },
  {
    id: "strava",
    name: "Strava",
    summary: "Activities, fitness trends, training load, and goals.",
    description: "Access Strava activities, fitness trends, training load, and goals. Agents can query workout data, analyze performance, and track fitness progress.",
    transport: "remote",
    authType: "oauth",
    isOfficial: true,
    category: ["fitness", "health"],
    icon: "https://cdn.simpleicons.org/strava/white",
    url: "https://mcp.strava.com/sse",
  },
  {
    id: "uber",
    name: "Uber",
    summary: "Get Uber price & time estimates for any ride option.",
    description: "Access Uber ride estimates, pricing, and timing. Agents can query ride options, estimate costs, and check availability for any location.",
    transport: "remote",
    authType: "oauth",
    isOfficial: true,
    category: ["transport", "lifestyle"],
    icon: "https://cdn.simpleicons.org/uber/white",
    url: "https://mcp.uber.com/sse",
  },
  {
    id: "instacart",
    name: "Instacart",
    summary: "Groceries and more delivered as fast as 30 minutes.",
    description: "Access Instacart's grocery delivery platform. Agents can search products, create shopping lists, and place delivery orders.",
    transport: "remote",
    authType: "oauth",
    isOfficial: true,
    category: ["lifestyle", "shopping"],
    icon: "https://cdn.simpleicons.org/instacart/white",
    url: "https://mcp.instacart.com/sse",
  },
  {
    id: "doordash",
    name: "DoorDash",
    summary: "Food delivery & reservations.",
    description: "Access DoorDash food delivery and restaurant reservations. Agents can search restaurants, place orders, and track deliveries.",
    transport: "remote",
    authType: "oauth",
    isOfficial: true,
    category: ["lifestyle", "food"],
    icon: "https://cdn.simpleicons.org/doordash/white",
    url: "https://mcp.doordash.com/sse",
  },
  {
    id: "intercom",
    name: "Intercom",
    summary: "AI access to Intercom data for customer insights.",
    description: "Access Intercom customer support data. Agents can search conversations, manage tickets, query customer profiles, and analyze support metrics.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["support", "business"],
    icon: "https://cdn.simpleicons.org/intercom/white",
    url: "https://mcp.intercom.com/sse",
    keyLabel: "Access Token",
    keyPlaceholder: "dGsk_...",
    keyHelpUrl: "https://developers.intercom.com/docs/references/authentication/",
  },
  {
    id: "pagerduty",
    name: "PagerDuty",
    summary: "Incidents, schedules, on-call.",
    description: "Manage PagerDuty incidents, schedules, and on-call rotations. Agents can query active incidents, manage schedules, and acknowledge alerts.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["devops", "monitoring"],
    icon: "https://cdn.simpleicons.org/pagerduty/white",
    url: "https://mcp.pagerduty.com/sse",
    keyLabel: "API Token",
    keyPlaceholder: "y_Nb...",
    keyHelpUrl: "https://support.pagerduty.com/docs/generating-api-keys",
  },
  {
    id: "incident-io",
    name: "incident.io",
    summary: "Incidents, on-call, follow-ups.",
    description: "Manage incidents, on-call schedules, and follow-ups in incident.io. Agents can declare incidents, assign roles, and track resolution progress.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["devops", "monitoring"],
    icon: "https://cdn.simpleicons.org/incidentdotio/white",
    url: "https://mcp.incident.io/sse",
    keyLabel: "API Key",
    keyPlaceholder: "inc_...",
    keyHelpUrl: "https://api-docs.incident.io/",
  },
  {
    id: "honeycomb",
    name: "Honeycomb",
    summary: "Query and explore observability data and SLOs.",
    description: "Query and explore observability data, traces, and SLOs in Honeycomb. Agents can run queries, analyze performance, and investigate anomalies.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["monitoring", "devops"],
    icon: "https://cdn.simpleicons.org/honeycomb/white",
    url: "https://mcp.honeycomb.io/sse",
    keyLabel: "API Key",
    keyPlaceholder: "Paste API key...",
    keyHelpUrl: "https://docs.honeycomb.io/manage-api-keys/",
  },
  {
    id: "mixpanel",
    name: "Mixpanel",
    summary: "Analyze, query, and manage your Mixpanel data.",
    description: "Analyze product analytics data in Mixpanel. Agents can run queries, create funnels, track events, and analyze user behavior patterns.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["analytics", "business"],
    icon: "https://cdn.simpleicons.org/mixpanel/white",
    url: "https://mcp.mixpanel.com/sse",
    keyLabel: "Service Account",
    keyPlaceholder: "Paste service account...",
    keyHelpUrl: "https://mixpanel.com/settings/project#service-accounts",
  },
  {
    id: "amplitude",
    name: "Amplitude",
    summary: "Give your teams powerful behavioral insights.",
    description: "Access Amplitude's behavioral analytics platform. Agents can query user behavior, analyze funnels, track retention, and generate insights.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["analytics", "business"],
    icon: "https://cdn.simpleicons.org/amplitude/white",
    url: "https://mcp.amplitude.com/sse",
    keyLabel: "API Key",
    keyPlaceholder: "Paste API key...",
    keyHelpUrl: "https://amplitude.com/docs/find-amplitude-api-id-and-key",
  },
  {
    id: "ramp",
    name: "Ramp",
    summary: "Search, access, and analyze your Ramp financial data.",
    description: "Access Ramp's corporate spend management platform. Agents can query transactions, analyze expenses, manage cards, and track spend patterns.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["finance", "business"],
    icon: "https://cdn.simpleicons.org/ramp/white",
    url: "https://mcp.ramp.com/sse",
    keyLabel: "API Key",
    keyPlaceholder: "sk_ramp_...",
    keyHelpUrl: "https://docs.ramp.com/developer-api/v1/overview",
  },
  {
    id: "xero",
    name: "Xero",
    summary: "Access your Xero financials from any conversation.",
    description: "Access Xero's accounting platform. Agents can query financial data, manage invoices, track bank transactions, and handle business accounting.",
    transport: "remote",
    authType: "oauth",
    isOfficial: true,
    category: ["finance", "accounting"],
    icon: "https://cdn.simpleicons.org/xero/white",
    url: "https://mcp.xero.com/sse",
  },
  {
    id: "apollo-io",
    name: "Apollo.io",
    summary: "Contacts, companies, sales engagement.",
    description: "Access Apollo.io's sales intelligence platform. Agents can search contacts, enrich company data, and manage sales engagement sequences.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["sales", "business"],
    icon: "https://cdn.simpleicons.org/apolloio/white",
    url: "https://mcp.apollo.io/sse",
    keyLabel: "API Key",
    keyPlaceholder: "Paste API key...",
    keyHelpUrl: "https://app.apollo.io/settings/integrations/api-key",
  },
  {
    id: "attio",
    name: "Attio",
    summary: "CRM records, notes, tasks.",
    description: "Access Attio's CRM platform. Agents can manage records, create notes, assign tasks, and query customer relationship data.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["crm", "business"],
    icon: "https://cdn.simpleicons.org/attio/white",
    url: "https://mcp.attio.com/sse",
    keyLabel: "API Key",
    keyPlaceholder: "Paste API key...",
    keyHelpUrl: "https://developers.attio.com/docs/api-key",
  },
  {
    id: "close",
    name: "Close",
    summary: "CRM leads, calls, pipelines.",
    description: "Access Close CRM platform. Agents can manage leads, log calls, track pipelines, and automate sales workflows.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["crm", "sales"],
    icon: "https://cdn.simpleicons.org/close/white",
    url: "https://mcp.close.com/sse",
    keyLabel: "API Key",
    keyPlaceholder: "Paste API key...",
    keyHelpUrl: "https://app.close.com/settings/api/",
  },
  {
    id: "docusing",
    name: "DocuSign",
    summary: "Agreements, envelopes, signing.",
    description: "Access DocuSign's e-signature platform. Agents can create envelopes, send for signature, track document status, and manage agreements.",
    transport: "remote",
    authType: "oauth",
    isOfficial: true,
    category: ["legal", "business"],
    icon: "https://cdn.simpleicons.org/docusign/white",
    url: "https://mcp.docusign.com/sse",
  },
  {
    id: "sanity",
    name: "Sanity",
    summary: "Create, query, and manage structured content.",
    description: "Access Sanity's structured content platform. Agents can query content, create documents, manage schemas, and publish content changes.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["cms", "content"],
    icon: "https://cdn.simpleicons.org/sanity/white",
    url: "https://mcp.sanity.io/sse",
    keyLabel: "API Token",
    keyPlaceholder: "sk...",
    keyHelpUrl: "https://www.sanity.io/manage/personal/api-tokens",
  },
  {
    id: "wordpress",
    name: "WordPress.com",
    summary: "Secure AI access to manage your WordPress.com sites.",
    description: "Manage WordPress.com sites. Agents can create posts, manage pages, moderate comments, and handle site configuration.",
    transport: "remote",
    authType: "oauth",
    isOfficial: true,
    category: ["cms", "content"],
    icon: "https://cdn.simpleicons.org/wordpress/white",
    url: "https://mcp.wordpress.com/sse",
  },
  {
    id: "wix",
    name: "Wix",
    summary: "Sites, stores, bookings.",
    description: "Manage Wix sites, stores, and bookings. Agents can update site content, manage products, and handle booking schedules.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["cms", "hosting", "commerce"],
    icon: "https://cdn.simpleicons.org/wix/white",
    url: "https://mcp.wix.com/sse",
    keyLabel: "API Key",
    keyPlaceholder: "Paste API key...",
    keyHelpUrl: "https://dev.wix.com/docs/go/api/wix-business-management/app-keys",
  },
  {
    id: "make",
    name: "Make",
    summary: "Run Make scenarios and manage your account.",
    description: "Access Make's automation platform. Agents can run scenarios, manage integrations, and automate complex workflows across connected services.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["automation", "productivity"],
    icon: "https://cdn.simpleicons.org/make/white",
    url: "https://mcp.make.com/sse",
    keyLabel: "API Key",
    keyPlaceholder: "Paste API key...",
    keyHelpUrl: "https://www.make.com/en/help/api-documentation",
  },
  {
    id: "neon",
    name: "Neon",
    summary: "Postgres projects, branches, SQL, docs.",
    description: "Access Neon's serverless Postgres platform. Agents can manage databases, create branches, run SQL queries, and access project documentation.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["database", "backend"],
    icon: "https://cdn.simpleicons.org/neon/white",
    url: "https://mcp.neon.tech/sse",
    keyLabel: "API Key",
    keyPlaceholder: "neon_...",
    keyHelpUrl: "https://neon.tech/docs/manage/api-keys",
  },
  {
    id: "microsoft-learn",
    name: "Microsoft Learn",
    summary: "Search trusted Microsoft docs to power your development.",
    description: "Access Microsoft Learn documentation. Agents can search docs, find API references, and get guidance on Microsoft technologies and frameworks.",
    transport: "remote",
    authType: "open",
    isOfficial: true,
    category: ["documentation", "development"],
    icon: "https://cdn.simpleicons.org/microsoft/white",
    url: "https://mcp.microsoft.com/learn/sse",
  },
  {
    id: "mintlify",
    name: "Mintlify",
    summary: "Search, read, and edit your documentation.",
    description: "Access Mintlify documentation platform. Agents can search docs, read content, and edit documentation for your projects.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["documentation", "development"],
    icon: "https://cdn.simpleicons.org/mintlify/white",
    url: "https://mcp.mintlify.com/sse",
    keyLabel: "API Key",
    keyPlaceholder: "ml_...",
    keyHelpUrl: "https://mintlify.com/docs/api",
  },
  {
    id: "browserbase",
    name: "Browserbase",
    summary: "Automate browser interactions in the cloud.",
    description: "Automate browser interactions in the cloud — web navigation, data extraction, form filling, and more. Agents can control headless browsers without local setup.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["browser", "automation", "web"],
    icon: "https://cdn.simpleicons.org/browserbase/white",
    url: "https://mcp.browserbase.com/sse",
    keyLabel: "API Key",
    keyPlaceholder: "bb_...",
    keyHelpUrl: "https://www.browserbase.com/settings",
  },
  {
    id: "parallel-search",
    name: "Parallel Search",
    summary: "Real-time web search and content extraction.",
    description: "Real-time web search and content extraction. Agents can search the web, extract page content, and retrieve structured data from any URL.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["search", "web"],
    icon: "<svg viewBox='0 0 24 24' fill='none' stroke='#e0e0e0' stroke-width='1.5' stroke-linecap='round' stroke-linejoin='round'><path d='M3 12h4l3-9 4 18 3-9h4'/></svg>",
    url: "https://mcp.parallel.ai/sse",
    keyLabel: "API Key",
    keyPlaceholder: "Paste API key...",
    keyHelpUrl: "https://parallel.ai/settings",
  },
  {
    id: "mercury",
    name: "Mercury",
    summary: "Accounts, transactions, balances, cards.",
    description: "Access Mercury's banking platform. Agents can query accounts, track transactions, check balances, and manage corporate cards.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["finance", "banking"],
    icon: "https://cdn.simpleicons.org/mercury/white",
    url: "https://mcp.mercury.com/sse",
    keyLabel: "API Token",
    keyPlaceholder: "Paste API token...",
    keyHelpUrl: "https://docs.mercury.com/reference",
  },
  {
    id: "ahrefs",
    name: "Ahrefs",
    summary: "SEO & AI search analytics.",
    description: "Access Ahrefs' SEO and search analytics platform. Agents can query backlinks, analyze search rankings, research keywords, and track SEO performance.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["seo", "marketing"],
    icon: "https://cdn.simpleicons.org/ahrefs/white",
    url: "https://mcp.ahrefs.com/sse",
    keyLabel: "API Token",
    keyPlaceholder: "Paste API token...",
    keyHelpUrl: "https://ahrefs.com/api/profile",
  },
  {
    id: "semrush",
    name: "Semrush",
    summary: "SEO, market data, and brand visibility insights.",
    description: "Access Semrush's SEO and marketing analytics platform. Agents can research keywords, analyze competitors, track rankings, and audit sites.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["seo", "marketing"],
    icon: "https://cdn.simpleicons.org/semrush/white",
    url: "https://mcp.semrush.com/sse",
    keyLabel: "API Key",
    keyPlaceholder: "Paste API key...",
    keyHelpUrl: "https://www.semrush.com/kb/41-api-keys",
  },
  {
    id: "similarweb",
    name: "Similarweb",
    summary: "Real time web, mobile app, and market data.",
    description: "Access Similarweb's market intelligence platform. Agents can analyze web traffic, compare competitors, and query market data across industries.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["analytics", "marketing"],
    icon: "https://cdn.simpleicons.org/similarweb/white",
    url: "https://mcp.similarweb.com/sse",
    keyLabel: "API Key",
    keyPlaceholder: "Paste API key...",
    keyHelpUrl: "https://www.similarweb.com/corp/api/",
  },
  {
    id: "granola",
    name: "Granola",
    summary: "The AI notepad for meetings.",
    description: "Connect AI tools to your Granola meeting notes via MCP. Agents can query notes, search transcripts, and get meeting insights.",
    transport: "remote",
    authType: "oauth",
    isOfficial: true,
    category: ["communication", "productivity"],
    icon: "https://cdn.simpleicons.org/granola/white",
    url: "https://mcp.granola.ai/sse",
  },
  {
    id: "fireflies",
    name: "Fireflies",
    summary: "Meeting transcripts, summaries, search.",
    description: "Access Fireflies.ai meeting intelligence. Agents can search transcripts, query meeting summaries, and extract action items from recorded meetings.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["communication", "productivity"],
    icon: "https://cdn.simpleicons.org/fireflies/white",
    url: "https://mcp.fireflies.ai/sse",
    keyLabel: "API Key",
    keyPlaceholder: "Paste API key...",
    keyHelpUrl: "https://app.fireflies.ai/api/webhooks",
  },
  {
    id: "otter-ai",
    name: "Otter.ai",
    summary: "Unlock your meeting intelligence.",
    description: "Access Otter.ai's meeting transcription platform. Agents can query transcripts, search meeting content, and extract action items.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["communication", "productivity"],
    icon: "https://cdn.simpleicons.org/otterai/white",
    url: "https://mcp.otter.ai/sse",
    keyLabel: "API Key",
    keyPlaceholder: "Paste API key...",
    keyHelpUrl: "https://otter.ai/api",
  },
  {
    id: "gamma",
    name: "Gamma",
    summary: "Presentations, documents, websites.",
    description: "Access Gamma's presentation and document platform. Agents can create presentations, generate documents, and publish websites using AI-powered design.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["design", "productivity"],
    icon: "https://cdn.simpleicons.org/gamma/white",
    url: "https://mcp.gamma.app/sse",
    keyLabel: "API Key",
    keyPlaceholder: "Paste API key...",
    keyHelpUrl: "https://gamma.app/docs/api",
  },
  {
    id: "gusto-payroll",
    name: "Workable",
    summary: "Your AI assistant for Hiring and HR.",
    description: "Access Workable's HR and hiring platform. Agents can manage job postings, search candidates, and track hiring pipelines.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["hr", "business"],
    icon: "https://cdn.simpleicons.org/workable/white",
    url: "https://mcp.workable.com/sse",
    keyLabel: "API Key",
    keyPlaceholder: "Paste API key...",
    keyHelpUrl: "https://dev.workable.com/",
  },
  {
    id: "indeed",
    name: "Indeed",
    summary: "Job search and listings.",
    description: "Access Indeed's job search platform. Agents can search job listings, query salary data, and find employment opportunities.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["hr", "jobs"],
    icon: "https://cdn.simpleicons.org/indeed/white",
    url: "https://mcp.indeed.com/sse",
    keyLabel: "API Key",
    keyPlaceholder: "Paste API key...",
    keyHelpUrl: "https://developers.indeed.com/",
  },
  {
    id: "survey-monkey",
    name: "SurveyMonkey",
    summary: "Design surveys, collect responses, and analyze results.",
    description: "Access SurveyMonkey's survey platform. Agents can create surveys, collect responses, and analyze results data.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["research", "business"],
    icon: "https://cdn.simpleicons.org/surveymonkey/white",
    url: "https://mcp.surveymonkey.com/sse",
    keyLabel: "Access Token",
    keyPlaceholder: "Paste access token...",
    keyHelpUrl: "https://developer.surveymonkey.com/api/v3/",
  },
  {
    id: "cloudinary",
    name: "Cloudinary",
    summary: "Manage, transform and deliver your images & videos.",
    description: "Access Cloudinary's media management platform. Agents can upload, transform, optimize, and deliver images and videos at scale.",
    transport: "remote",
    authType: "apikey",
    isOfficial: true,
    category: ["media", "development"],
    icon: "https://cdn.simpleicons.org/cloudinary/white",
    url: "https://mcp.cloudinary.com/sse",
    keyLabel: "API Key",
    keyPlaceholder: "Paste API key...",
    keyHelpUrl: "https://cloudinary.com/documentation/api_keys",
  },
  {
    id: "godot",
    name: "Godot MCP",
    summary: "300+ tools that connect AI assistants to the Godot editor.",
    description: "Connect AI assistants directly to the Godot game engine editor. Agents can build scenes, write scripts, test gameplay, and manage project assets — all through natural language.",
    transport: "stdio",
    authType: "open",
    isOfficial: false,
    category: ["game-dev", "development"],
    icon: "https://cdn.simpleicons.org/godotengine/white",
    command: "npx",
    args: ["-y", "@godot-mcp/godot-mcp"],
    nativeIntegration: true,
    nativeIntegrationNote:
      "Game dev station: agents work on Godot projects with a visible scene tree panel. Perfect for agents building games or interactive experiences.",
  },
  {
    id: "xcode-build",
    name: "XcodeBuildMCP",
    summary: "Build, test, and manage iOS/macOS projects.",
    description: "A Model Context Protocol (MCP) server and CLI that provides tools for agent use when working on iOS and macOS projects. Agents can build, test, and manage Xcode projects.",
    transport: "stdio",
    authType: "open",
    isOfficial: false,
    category: ["development", "mobile"],
    icon: "https://cdn.simpleicons.org/xcode/white",
    command: "npx",
    args: ["-y", "@xcodebuildmcp/xcodebuildmcp"],
  },
  {
    id: "nextjs-devtools",
    name: "Next.js DevTools",
    summary: "Next.js development tools for AI coding assistants.",
    description: "next-devtools-mcp is an MCP server that provides Next.js development tools and utilities for AI coding assistants like Claude and Cursor. Agents can inspect routes, manage configs, and debug Next.js apps.",
    transport: "stdio",
    authType: "open",
    isOfficial: true,
    category: ["development", "web"],
    icon: "https://cdn.simpleicons.org/nextdotjs/white",
    command: "npx",
    args: ["-y", "@vercel/next-devtools-mcp"],
  },
  {
    id: "proxyman",
    name: "Proxyman MCP",
    summary: "Inspect HTTP traffic, create debugging rules, control Proxyman.",
    description: "Proxyman MCP allows AI to inspect HTTP traffic, create debugging rules, and control Proxyman — all through natural language conversations. Agents can analyze network requests and debug API issues.",
    transport: "stdio",
    authType: "open",
    isOfficial: true,
    category: ["development", "debugging"],
    icon: "https://cdn.simpleicons.org/proxyman/white",
    command: "npx",
    args: ["-y", "@proxyman/proxyman-mcp"],
  },
  {
    id: "yahoo-finance",
    name: "Yahoo Finance",
    summary: "Stock data, market news, financials, and price history.",
    description:
      "Remote MCP server providing access to Yahoo Finance market data. Agents can fetch stock quotes, historical price data, company financials, market news, and key statistics. No authentication required — works out of the box. Perfect as a read-only data source for analysis agents that feed trading decisions to execution agents.",
    transport: "remote",
    authType: "open",
    isOfficial: false,
    category: ["finance", "trading", "data"],
    icon: "https://cdn.simpleicons.org/yahoofinance/white",
    url: "https://gateway.mcpservers.org/yahoo-finance/mcp",
  },
  {
    id: "pulsemcp",
    name: "PulseMCP",
    summary: "Search and discover 22k+ MCP servers across the ecosystem.",
    description:
      "An MCP server that provides tools for discovering and exploring MCP servers and integrations through the PulseMCP API. Agents can search the entire PulseMCP ecosystem (22,000+ servers) using list_servers with optional query filtering, and list all available integrations with list_integrations. Perfect for finding the right MCP server for a task when the curated catalog doesn't have what you need.",
    transport: "stdio",
    authType: "open",
    isOfficial: false,
    category: ["search", "discovery", "mcp"],
    icon: "<svg viewBox='0 0 24 24' fill='none' stroke='#e0e0e0' stroke-width='1.5' stroke-linecap='round' stroke-linejoin='round'><path d='M22 12h-4l-3 9L9 3l-3 9H2'/></svg>",
    command: "npx",
    args: ["-y", "pulsemcp-server"],
    nativeIntegration: true,
    nativeIntegrationNote:
      "Discovery terminal: when an agent searches PulseMCP, show results scrolling on their monitor like a search engine. Results appear as installable cards.",
  },
];

// ── Helper functions ───────────────────────────────────────────────────

/** All unique category tags across the catalog. */
export const MCP_CATEGORIES: string[] = [...new Set(MCP_CATALOG.flatMap((s) => s.category))].sort();

/** Search the catalog by text query. */
export function searchCatalog(query: string): MCPCatalogServer[] {
  const q = query.toLowerCase().trim();
  if (!q) return MCP_CATALOG;
  return MCP_CATALOG.filter((s) =>
    s.name.toLowerCase().includes(q) ||
    s.summary.toLowerCase().includes(q) ||
    s.description.toLowerCase().includes(q) ||
    s.category.some((c) => c.toLowerCase().includes(q)),
  );
}

/** Filter the catalog by category. */
export function filterByCategory(category: string): MCPCatalogServer[] {
  return MCP_CATALOG.filter((s) => s.category.includes(category));
}

/** Get a server by ID. */
export function getServerById(id: string): MCPCatalogServer | undefined {
  return MCP_CATALOG.find((s) => s.id === id);
}

/** Get a server by its remote URL. Used to look up icon/branding for agents
 *  whose MCPServerConfig was persisted before the `icon` field was added. */
export function getServerByUrl(url: string): MCPCatalogServer | undefined {
  return MCP_CATALOG.find((s) => s.url === url);
}

/**
 * Build a compact categorized summary of the curated MCP catalog.
 * Used to inject knowledge into Yuki's context so she can recommend
 * MCP servers to users without browsing the marketplace.
 */
export function catalogSummary(): string {
  const byCategory: Record<string, { name: string; summary: string; auth: string }[]> = {};
  for (const s of MCP_CATALOG) {
    const entry = { name: s.name, summary: s.summary, auth: s.authType };
    for (const cat of s.category) {
      if (!byCategory[cat]) byCategory[cat] = [];
      if (!byCategory[cat].some((e) => e.name === s.name)) {
        byCategory[cat].push(entry);
      }
    }
  }
  const lines: string[] = [];
  for (const cat of Object.keys(byCategory).sort()) {
    const items = byCategory[cat];
    lines.push(`  ${cat}:`);
    for (const item of items) {
      const authTag = item.auth === "open" ? " (no auth)" : item.auth === "oauth" ? " (OAuth)" : " (API key)";
      lines.push(`    - ${item.name}${authTag}: ${item.summary}`);
    }
  }
  return lines.join("\n");
}

/**
 * Build a summary of notable curated marketplace agents.
 * These are the seed agents from the Supabase migrations — big tech,
 * proven services. Yuki uses this to recommend specific agents.
 */
export const CURATED_AGENTS_SUMMARY = `### Curated Marketplace Agents (hire via MARKET button)
- Yahoo Finance Agent: Strategy evaluator — fetches market data, computes technical indicators inline (RSI, MACD, SMA, Bollinger Bands), evaluates strategy conditions, and emits structured trade signals. No auth needed. Pairs with Robinhood agent via schedule + handoff.
- Robinhood Trading Agent: Trade executor — receives trade signal handoffs from analysis agents, confirms with boss, places trades via Robinhood MCP (OAuth). Always requires human confirmation before executing.
- GitHub Agent: Dev agent — manage repos, issues, PRs, and code search via GitHub MCP. Requires Personal Access Token.`;


/** Convert a catalog entry to an MCPServerConfig for agent assignment. */
export function toMCPServerConfig(server: MCPCatalogServer): import("./types.js").MCPServerConfig {
  const config: import("./types.js").MCPServerConfig = {
    name: server.name,
  };
  if (server.transport === "remote" && server.url) {
    config.url = server.url;
  } else if (server.transport === "stdio" && server.command) {
    config.command = server.command;
    config.args = server.args;
  }
  if (server.authType === "oauth") {
    config.authType = "oauth";
  } else if (server.authType === "apikey") {
    config.authType = "apikey";
  }
  if (server.keyLabel) config.keyLabel = server.keyLabel;
  if (server.keyPlaceholder) config.keyPlaceholder = server.keyPlaceholder;
  if (server.keyHelpUrl) config.keyHelpUrl = server.keyHelpUrl;
  if (server.icon) config.icon = server.icon;
  return config;
}
